{
 "title": "Services API Testing",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "content": "<p align=\"center\"><img  src=\"https://cdn3.iconfinder.com/data/icons/linecons-free-vector-icons-pack/32/mail-512.png\" width=\"30dp\" /> <h2>Email Notification Services</h2></p>\n\n\n\n\n"
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "content": "<p align=\"center\"><img  src=\"https://www.stickpng.com/assets/images/580b57fbd9996e24bc43bdf2.png\" width=\"30dp\" /> <h2>Android Push Notification Services</h2></p>\n"
  },
  {
   "title": "Email API Status",
   "type": "snuids-trafficlights-panel",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  status_code\nFROM tbl_api_details\nWHERE\napi_name = \"emailNotificationsTest\"\nand\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Email API Response Time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 4, "y": 3 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  response_time\nFROM tbl_api_details\nWHERE\napi_name = \"emailNotificationsTest\"\nand\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Android Push API Status",
   "type": "snuids-trafficlights-panel",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  status_code\nFROM tbl_api_details\nWHERE\napi_name = \"pushNotificationsAndroid\"\nand\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Android Push Response Time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 3 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  response_time\nFROM tbl_api_details\nWHERE\napi_name=\"pushNotificationsAndroid\"\nAnd\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Email API Response Time Status",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 4, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  response_time\nFROM tbl_api_details\nWHERE\napi_name=\"emailNotificationsTest\"\nAnd\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Android Push Response Time Status",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  response_time\nFROM tbl_api_details\nWHERE\napi_name=\"pushNotificationsAndroid\"\nand\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Email API Response Time Trend",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(timestamp,$__interval),\n  response_time AS \"response_time\"\nFROM tbl_api_details\nWHERE\n  $__timeFilter(timestamp)\nGROUP BY 1\nORDER BY $__timeGroup(timestamp,$__interval)"
    }
   ]
  },
  {
   "title": "Email API Response Time Trend",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(timestamp,$__interval),\n  response_time AS \"response_time\"\nFROM tbl_api_details\nWHERE\n  $__timeFilter(timestamp)\nGROUP BY 1\nORDER BY $__timeGroup(timestamp,$__interval)"
    }
   ]
  }
 ]
}